In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [216]:
# STEP 1
myDF = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/test.csv')

In [178]:
# STEP 2
print(myDF.head())

   10    192    50  F  NXEYEM
0  20  299.0  21.0  M  VNFKZD
1  30  378.0  28.0  X  IMGMFY
2  40  156.0  44.0  Q  RHRHJY
3  50  468.0  33.0  J  HPQCMC
4  60  347.0  38.0  X  XFEWVB

In [217]:
# STEP 3
if myDF.columns[0] != 'ID':
    myDF.columns = ['ID', 'Range', 'Value', 'Machine Type', 'Zip code']

In [218]:
# EXTRA STEP  TO CHECK NUMBER OF COLUMNS
print(myDF.columns)

print("Number of columns:", len(myDF.columns))

Index(['ID', 'Range', 'Value', 'Machine Type', 'Zip code'], dtype='object')
Number of columns: 5

In [219]:
# STEP 4
new_row = pd.DataFrame({'Name': ['VEDANTSINH GOHEL'], 'Student Number': ['101398199']})
myDF = pd.concat([new_row, myDF], ignore_index=True)

myDF.to_csv('modified_test.csv', index=False)
print(myDF.head())

               Name Student Number   ID  Range  Value Machine Type Zip code
0  VEDANTSINH GOHEL      101398199  NaN    NaN    NaN          NaN      NaN
1               NaN            NaN   20  299.0   21.0            M   VNFKZD
2               NaN            NaN   30  378.0   28.0            X   IMGMFY
3               NaN            NaN   40  156.0   44.0            Q   RHRHJY
4               NaN            NaN   50  468.0   33.0            J   HPQCMC

In [231]:
# STEP 5
myDF = pd.read_csv('modified_test.csv', skiprows=[1])

print(myDF.head())

   Name  Student Number  ID  Range  Value Machine Type Zip code
0   NaN             NaN  20  299.0   21.0            M   VNFKZD
1   NaN             NaN  30  378.0   28.0            X   IMGMFY
2   NaN             NaN  40  156.0   44.0            Q   RHRHJY
3   NaN             NaN  50  468.0   33.0            J   HPQCMC
4   NaN             NaN  60  347.0   38.0            X   XFEWVB

In [232]:
# STEP 6
print(type(myDF))

<class 'pandas.core.frame.DataFrame'>

In [233]:
# STREP 7
value_column_1 = myDF['Value']
value_column_2 = myDF.Value
# Both methods are equivalent, but the second one is more object-oriented

In [234]:
# STEP 8
print(type(value_column_1))

<class 'pandas.core.series.Series'>

In [235]:
# STEP 9
#No, we cannot apply both methods for fetching the 'Zip code' column because it has spaces in its name.
# Spaces in column names are not allowed for the second method (dot notation).

In [236]:
# STEP 10
myDF['Brand'] = myDF['Machine Type'] + myDF['Zip code']

In [187]:
# STEP 11
myDF['Total'] = myDF['Range'] * myDF['Value']

In [188]:
# STP 12
print(myDF.head())
print(myDF.describe())
print(myDF.describe)
print(myDF.shape)
print(myDF.dtypes)

               Name Student Number   ID  Range  Value Machine Type Zip code  \
0  VEDANTSINH GOHEL      101398199  NaN    NaN    NaN          NaN      NaN
1               NaN            NaN   20  299.0   21.0            M   VNFKZD
2               NaN            NaN   30  378.0   28.0            X   IMGMFY
3               NaN            NaN   40  156.0   44.0            Q   RHRHJY
4               NaN            NaN   50  468.0   33.0            J   HPQCMC

     Brand    Total
0      NaN      NaN
1  MVNFKZD   6279.0
2  XIMGMFY  10584.0
3  QRHRHJY   6864.0
4  JHPQCMC  15444.0
            Range       Value         Total
count  949.000000  949.000000    949.000000
mean   297.548999   29.922023   8965.324552
std    115.838955   12.256499   5264.017144
min    100.000000   10.000000   1090.000000
25%    194.000000   19.000000   4862.000000
50%    296.000000   30.000000   7912.000000
75%    399.000000   41.000000  12369.000000
max    500.000000   50.000000  24750.000000
<bound method NDFrame.describe of                  Name Student Number    ID  Range  Value Machine Type  \
0    VEDANTSINH GOHEL      101398199   NaN    NaN    NaN          NaN
1                 NaN            NaN    20  299.0   21.0            M
2                 NaN            NaN    30  378.0   28.0            X
3                 NaN            NaN    40  156.0   44.0            Q
4                 NaN            NaN    50  468.0   33.0            J
..                ...            ...   ...    ...    ...          ...
946               NaN            NaN  9460  136.0   12.0            C
947               NaN            NaN  9470  316.0   46.0            L
948               NaN            NaN  9480  461.0   46.0            K
949               NaN            NaN  9490  185.0   13.0            N
950               NaN            NaN  9500  137.0   10.0            W

    Zip code    Brand    Total
0        NaN      NaN      NaN
1     VNFKZD  MVNFKZD   6279.0
2     IMGMFY  XIMGMFY  10584.0
3     RHRHJY  QRHRHJY   6864.0
4     HPQCMC  JHPQCMC  15444.0
..       ...      ...      ...
946   HGVBPV  CHGVBPV   1632.0
947   SHBAUD  LSHBAUD  14536.0
948   PUZUVO  KPUZUVO  21206.0
949   UMESZO  NUMESZO   2405.0
950   JOHHVL  WJOHHVL   1370.0

[951 rows x 9 columns]>
(951, 9)
Name               object
Student Number     object
ID                 object
Range             float64
Value             float64
Machine Type       object
Zip code           object
Brand              object
Total             float64
dtype: object

In [189]:
# STEP 13
print(myDF.describe(include='object'))

                    Name Student Number   ID Machine Type Zip code    Brand
count                  1              1  950          947      940      938
unique                 1              1  950           26      940      938
top     VEDANTSINH GOHEL      101398199   20            F   VNFKZD  MVNFKZD
freq                   1              1    1           49        1        1

In [190]:
# STEP 14
myDF = myDF.rename(columns={'ID': 'My ID'})
print(myDF.head())

               Name Student Number My ID  Range  Value Machine Type Zip code  \
0  VEDANTSINH GOHEL      101398199   NaN    NaN    NaN          NaN      NaN
1               NaN            NaN    20  299.0   21.0            M   VNFKZD
2               NaN            NaN    30  378.0   28.0            X   IMGMFY
3               NaN            NaN    40  156.0   44.0            Q   RHRHJY
4               NaN            NaN    50  468.0   33.0            J   HPQCMC

     Brand    Total
0      NaN      NaN
1  MVNFKZD   6279.0
2  XIMGMFY  10584.0
3  QRHRHJY   6864.0
4  JHPQCMC  15444.0

In [191]:
#STEP 15
myDF.rename(columns={'My ID': 'ID'}, inplace=True)
print(myDF.head())

               Name Student Number   ID  Range  Value Machine Type Zip code  \
0  VEDANTSINH GOHEL      101398199  NaN    NaN    NaN          NaN      NaN
1               NaN            NaN   20  299.0   21.0            M   VNFKZD
2               NaN            NaN   30  378.0   28.0            X   IMGMFY
3               NaN            NaN   40  156.0   44.0            Q   RHRHJY
4               NaN            NaN   50  468.0   33.0            J   HPQCMC

     Brand    Total
0      NaN      NaN
1  MVNFKZD   6279.0
2  XIMGMFY  10584.0
3  QRHRHJY   6864.0
4  JHPQCMC  15444.0

In [192]:
#STEP 16
print(myDF.columns)

Index(['Name', 'Student Number', 'ID', 'Range', 'Value', 'Machine Type',
       'Zip code', 'Brand', 'Total'],
      dtype='object')

In [194]:
#STEP 17
myDF.columns = ['','','id', 'range', 'value', 'machine_type', 'zip_code', 'brand', 'total']

In [195]:
#STEP 18
myDF.columns = myDF.columns.str.replace(' ', '_')

In [196]:
#STEP 19
myDF.drop(['brand', 'total'], axis=1, inplace=True)

In [197]:
#STEP 20
myDF.drop([2, 4], inplace=True)

In [198]:
#STEP 21
print(myDF['value'].sort_values())

950    10.0
487    10.0
506    10.0
203    10.0
211    10.0
       ...
701    50.0
919    50.0
125    50.0
0       NaN
921     NaN
Name: value, Length: 949, dtype: float64

In [199]:
#STEP 22
print(myDF.sort_values(by='value'))

                                                            id  range  value  \
950               NaN        NaN                          9500  137.0   10.0
487               NaN        NaN                          4880  188.0   10.0
506               NaN        NaN                          5070  268.0   10.0
203               NaN        NaN                          2040  148.0   10.0
211               NaN        NaN                          2120  174.0   10.0
..                ...        ...                           ...    ...    ...
701               NaN        NaN                          7020  246.0   50.0
919               NaN        NaN                          9200  189.0   50.0
125               NaN        NaN                          1260  400.0   50.0
0    VEDANTSINH GOHEL  101398199                           NaN    NaN    NaN
921               NaN        NaN  #Reza Dibaj, ST ID=101280076    NaN    NaN

    machine_type zip_code
950            W   JOHHVL
487            I   AWADHV
506            N   WHIZNL
203            T   NRLBSZ
211            I   VZVNFW
..           ...      ...
701            Q   TELSOE
919            Y   BPHKFD
125            X   AHOATF
0            NaN      NaN
921          NaN      NaN

[949 rows x 7 columns]

In [200]:
#STEP 23
myDF.sort_values(by='value', inplace=True)

In [201]:
#STEP 24
myDF.sort_values(by=['range', 'value'], ascending=[True, False], inplace=True)

In [202]:
#STEP 25
print(myDF[(myDF['range'] >= 250) & (myDF['range'] <= 350)])

                 id  range  value machine_type zip_code
57   NaN  NaN   580  250.0   19.0            K   EFXWGS
262  NaN  NaN  2630  250.0   12.0            O   ZZIXOA
811  NaN  NaN  8120  251.0   49.0            D   QOWNHD
307  NaN  NaN  3080  251.0   26.0            Z   YCKPXV
276  NaN  NaN  2770  252.0   38.0            J   SKKOYK
..   ...  ...   ...    ...    ...          ...      ...
833  NaN  NaN  8340  350.0   46.0            K   NCUWLM
645  NaN  NaN  6460  350.0   30.0            Q   LVDEAS
738  NaN  NaN  7390  350.0   24.0            X      NaN
382  NaN  NaN  3830  350.0   14.0            M   FOIOWR
538  NaN  NaN  5390  350.0   10.0            J   WEUVDY

[205 rows x 7 columns]

In [203]:
#STEP 26
print(myDF[(myDF['range'] >= 250) & (myDF['range'] <= 350)].sort_values(by='range'))

                 id  range  value machine_type zip_code
57   NaN  NaN   580  250.0   19.0            K   EFXWGS
262  NaN  NaN  2630  250.0   12.0            O   ZZIXOA
811  NaN  NaN  8120  251.0   49.0            D   QOWNHD
307  NaN  NaN  3080  251.0   26.0            Z   YCKPXV
276  NaN  NaN  2770  252.0   38.0            J   SKKOYK
..   ...  ...   ...    ...    ...          ...      ...
738  NaN  NaN  7390  350.0   24.0            X      NaN
382  NaN  NaN  3830  350.0   14.0            M   FOIOWR
833  NaN  NaN  8340  350.0   46.0            K   NCUWLM
645  NaN  NaN  6460  350.0   30.0            Q   LVDEAS
538  NaN  NaN  5390  350.0   10.0            J   WEUVDY

[205 rows x 7 columns]

In [204]:
#STEP 27
print(myDF.loc[(myDF['range'] >= 250) & (myDF['range'] <= 350), ['id', 'value']])

       id  value
57    580   19.0
262  2630   12.0
811  8120   49.0
307  3080   26.0
276  2770   38.0
..    ...    ...
833  8340   46.0
645  6460   30.0
738  7390   24.0
382  3830   14.0
538  5390   10.0

[205 rows x 2 columns]

In [205]:
#STEP 28
print(myDF.loc[(myDF['range'] >= 250) & (myDF['range'] <= 350) & (myDF['machine_type'] == 'H'), ['id', 'value', 'machine_type']])

       id  value machine_type
302  3030   14.0            H
620  6210   47.0            H
438  4390   11.0            H
493  4940   16.0            H
445  4460   32.0            H
260  2610   50.0            H
611  6120   11.0            H
525  5260   32.0            H

In [206]:
#STEP 29
print(myDF[myDF['machine_type'].isin(['H', 'R', 'X'])])

                 id  range  value machine_type zip_code
871  NaN  NaN  8720  104.0   49.0            H   AGKGDY
749  NaN  NaN  7500  107.0   26.0            H   UKPFIJ
759  NaN  NaN  7600  112.0   32.0            H   QIEDLK
337  NaN  NaN  3380  114.0   22.0            X   RBNAEU
265  NaN  NaN  2660  121.0   23.0            H   XCNVOV
..   ...  ...   ...    ...    ...          ...      ...
920  NaN  NaN  9210  446.0   27.0            H   WQCBIF
395  NaN  NaN  3960  480.0   46.0            R   DOVCUA
279  NaN  NaN  2800  487.0   23.0            R   KDCJBV
28   NaN  NaN   290  487.0   16.0            X   WVVYSF
803  NaN  NaN  8040  496.0   27.0            R   NMLXEZ

[101 rows x 7 columns]

In [207]:
#STEP 30
print(myDF.dtypes)
print(myDF.select_dtypes(include='number'))

                 object
                 object
id               object
range           float64
value           float64
machine_type     object
zip_code         object
dtype: object
     range  value
504  100.0   21.0
462  101.0   26.0
798  101.0   20.0
556  102.0   15.0
751  103.0   44.0
..     ...    ...
411  500.0   27.0
731  500.0   20.0
423  500.0   17.0
0      NaN    NaN
921    NaN    NaN

[949 rows x 2 columns]